# Checked 예외

Checked 는 Catch 로 처리하거나 Throw 로 던지는 처리를 필수로 해야하는 예외이다.

## ✏️ Checked 예외 처리하기

### 📍Throw

- 연습용 새로운 예외 객체를 MyCheckedException 생성했다.
- Checked Exception 을 던질 때는 Method 이름 옆에 꼭 throws 선언을 해야 한다.

```java
package hello.jdbc.excepiton;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class CheckedTest {

    static class MyCheckedException extends Exception {

        /**
         * Exception 을 상속받은 예외는 체크 예외가 된다.
         */
        public MyCheckedException(String message) {
            super(message);
        }
    }

    // Checked Exception 을 던질 때는 Method 이름 옆에 꼭 선언을 해야 한다.
    static class Repository{
        public void call() throws MyCheckedException {
            throw new MyCheckedException("ex");
        }
    }

}
```

<br>

### 📍 Catch

- try , catch 를 사용해 예외를 처리할 수 있다.

```java
    static class Service{
        // Repository instance
        Repository repository = new Repository();

        // 예외를 처리하는 코드
        public void callCatch() {
            try {
                repository.call();
            } catch (MyCheckedException e) {
                // 예외 처리 로직
                log.info("예외 처리, message = {}", e.getMessage(), e);
            }
        }
    }
```

<br>

## ✏️ Test

### 📍 Catch

- Service 에서 예외처리를 끝냈기 때문에 정상 흐름으로 호출이 가능하다.

```java
    @Test
    void checked_catch() {
        Service service = new Service();
        service.callCatch();
    }
```

🔍 출력물 확인

- Repository 에서 예외를 던질 때 작성한 예외 메세지 “ex” 가 log.info 의 e.message 를 통해 출력됨
    - 예외 처리, message = e
- log.info 의 e 를 통해 예외의 발생 원인과 위치가 출력됨

```java
10:51:58.460 [main] INFO hello.jdbc.excepiton.CheckedTest - 예외 처리, message = ex
hello.jdbc.excepiton.CheckedTest$MyCheckedException: ex
	at hello.jdbc.excepiton.CheckedTest$Repository.call(CheckedTest.java:41)
	at hello.jdbc.excepiton.CheckedTest$Service.callCatch(CheckedTest.java:31)
	...
```

<br>

### 📍 Throw

이번엔 Service 에서 예외를 한번 더 던지는 method 를 만들었다.

```java
static class Service{
        Repository repository = new Repository();

        // 예외를 던지는 코드
        public void callThrow () throws MyCheckedException {
            repository.call();
        }

        // 예외를 처리하는 코드
        public void callCatch() {
            try {
                repository.call();
            } catch (MyCheckedException e) {
                // 예외 처리 로직
                log.info("예외 처리, message = {}", e.getMessage(), e);
            }
        }
    }
```

- method 호출
    - 처리되지 않은 예외를 가진 Method 를 호출해 MyCheckedException 에러가 발생하고 만다.

```java
    @Test
    void checked_throw(){
        Service service = new Service();
        assertThatThrownBy(() -> service.callThrow())
                .isInstanceOf(MyCheckedException.class);
    }
```

<br>

## ✏️ Checked 예외의 장단점

- 장점
    - 개발자가 실수로 예외를 누락하지 않도록 컴파일을 통해 문제를 잡아주는 안전장치 역할을 해준다.
- 단점
    - 개발자가 모든 체크 예외를 반드시 잡거나 던지도록 처리해야 하기 때문에 너무 번거로운 일이 된다.
    - 사사로운 예외까지 모두 챙겨야만 한다.
    - 의존관계에 따른 단점도 발생한다. 🔗
        - Repository 에서 넘어온 Contoller 에서 처리할 수 있는 예외를 Service 가 중간에서 하나하나 Throw 해줘야 한다.